### ISSUE TITLE
More info?

### ISSUE THREAD

**Issue by sardaukar** [wheremyfoodat/Gameboy-logs#1]
Would it be possible to add more info to the logs? Like MMIO values and so on?

**Comment by wheremyfoodat** [comment]
Hello there!
What do you mean add more info to the logs about MMIO? These ROMs shouldn't do much IO stuff other than initializing the display, playing a small sound (like the bootrom does), writing text to the serial port (like Blargg does), and polling the LY register (which is stubbed to 0x90 as the readme says).

What would you like to see?

**Comment by sardaukar** [comment]
I meant adding the state of the rest of the hardware, like:

```
[000000] AF:0x0000 BC:0x0000 DE:0x0000 HL:0x0000 | SP:0xfffe | PC:0x03 | LCDC:0x00 STAT:0x00 SCY:0x00 SCX:0x00 LY:0x00 LYC:0x00 DMA:0x00 BGP:0x00 OBP0:0x00 OBP1:0x00 WY:0x00 WX:0x00 MODECLOCK:12 PPU MODE:1
```

So that's the iteration number, registers, stack pointer, PC, and the memory-mapped IO registers, plus the PPU modeclock and mode

**Comment by wheremyfoodat** [comment]
That would get confusing very quick. Most people using these logs don't even have any IO implemented while stuff like the mode clock would be ever worse because that depends on the exact PPU configuration (settings like scrolling and sprites make certain modes take more time, there's a ton of edge cases that depend on the GB model, etc)

So yeah I think just regs are sufficient
